"""응답 코드 중앙 관리

시스템 코드를 중앙에서 관리하여 일관성을 유지합니다.
"""


class ResponseCode:
    """응답 코드 상수"""

    # 성공 코드
    RECIPE_CREATED = "RECIPE_CREATED"
    RECOMMENDATION_SUCCESS = "RECOMMENDATION_SUCCESS"
    QUESTION_ANSWERED = "QUESTION_ANSWERED"

    # 에러 코드
    RECIPE_PARSE_ERROR = "RECIPE_PARSE_ERROR"
    RECOMMENDATION_PARSE_ERROR = "RECOMMENDATION_PARSE_ERROR"
    QUESTION_PARSE_ERROR = "QUESTION_PARSE_ERROR"
    IMAGE_GENERATION_FAILED = "IMAGE_GENERATION_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    WORKFLOW_ERROR = "WORKFLOW_ERROR"
    INVALID_INTENT = "INVALID_INTENT"